### ISSUE TITLE
Uncaught Error: translation: 'auth.signIn' on locale: 'null' was not found

### ISSUE THREAD

**Issue by ryrych** [yahoo/ember-intl#244]
```javascript
import Ember from 'ember';
import hbs from 'htmlbars-inline-precompile';
import { moduleForComponent, test } from 'ember-qunit';
import instanceInitializer from 'ntfrontend/instance-initializers/ember-intl';

moduleForComponent('auth-button', 'Integration | Component | auth button', {
  integration: true,
  setup() {
    instanceInitializer.initialize(this);
    const intl = this.container.lookup('service:intl');
    intl.setLocale('en-us');
  },
[…]
});
```

```html
    {{content-for 'body'}}
    {{content-for 'test-body'}}
    <script src="assets/intl/intl.min.js"></script>
    <script src="assets/intl/locales/en-us.js"></script>
    <script src="assets/vendor.js"></script>
```

```yaml
# translations/auth/en-us.yaml
auth:
  signUp: "Sign up"
  signIn: "Sign In"
  logout: "Logout"
```
